**OOP**

  * Constructor or Initialiser in class

In [1]:
class Visitors:
    def __init__(self, name, age , city):                      #constructor or intialiser - executes 1st and executes on its own
        self.details = {"Name" : name , "Age" : age , "City" : city}

    def add_department(self, dept):
        self.details['department'] = dept

    def show_visitor_details(self):
        return self.details

In [2]:
v1 = Visitors("Ram" , 22 , "Delhi")
v2 = Visitors("Jai" , 19 , "Jaipur")
v3 = Visitors("Gagan" , 21 , "Indore")

In [3]:
v1.show_visitor_details()

{'Name': 'Ram', 'Age': 22, 'City': 'Delhi'}

In [4]:
v2.show_visitor_details()

{'Name': 'Jai', 'Age': 19, 'City': 'Jaipur'}

In [5]:
v3.show_visitor_details()

{'Name': 'Gagan', 'Age': 21, 'City': 'Indore'}

**Create a Python class named BankAccount with the following attributes and methods:**

    * Attributes: account_number, account_holder, balance
    Methods:
        - deposit(amount): Adds the specified amount to the balance.
        - withdraw(amount): Deducts the specified amount from the balance if sufficient funds are available. Otherwise, prints "Insufficient balance."
        - display_balance(): Displays the current balance.

* Write a script to create an instance of the class and demonstrate all the methods.

In [6]:
class BankAccount:
  def __init__(self,account_number,account_holder,balance):
    self.account_number = account_number
    self.account_holder = account_holder
    self.balance = balance

  def deposit(self,amount):
    self.balance += amount

  def withdraw(self,amount):
    if amount < self.balance:
      self.balance -= amount
      return "Withdrawl successfull"
    else:
      return "Insufficient balance"

  def display_balance(self):
    details = {"Name" : self.account_holder , "Balance" : self.balance}
    return details

In [7]:
rahul = BankAccount("9754357785" , "Rahul" , 20000)
anita = BankAccount("9754557854" , "Anita" , 15000)

In [8]:
print(rahul.account_number , rahul.account_holder , rahul.balance)

9754357785 Rahul 20000


In [9]:
print(anita.account_number , anita.account_holder , anita.balance)

9754557854 Anita 15000


In [10]:
rahul.deposit(40000)
print(rahul.account_number , rahul.account_holder , rahul.balance)

9754357785 Rahul 60000


In [11]:
status = anita.withdraw(5000)
print(status)
print(anita.account_number , anita.account_holder , anita.balance)

Withdrawl successfull
9754557854 Anita 10000


In [12]:
status = anita.withdraw(50000)
print(status)
print(anita.account_number , anita.account_holder , anita.balance)

Insufficient balance
9754557854 Anita 10000


In [13]:
rahul.display_balance()

{'Name': 'Rahul', 'Balance': 60000}

In [14]:
anita.display_balance()

{'Name': 'Anita', 'Balance': 10000}

**Python for Data Science**
   * Numpy - Numerical Python
   * Pandas
   * Matplotlib
   * Seaborn

In [15]:
val = 20
print(val * 3)

60


In [16]:
values = [5 , 8 , 3 , 2 , 7]
print(values * 2)

[5, 8, 3, 2, 7, 5, 8, 3, 2, 7]


In [17]:
def perform_multiplication(values , num):
  output = []
  for val in values:
    output.append(val * num)
  return output

In [18]:
print(perform_multiplication([7,9,4,3] , 2))
print(perform_multiplication([7,9,4,3,8,3,6] , 4))

[14, 18, 8, 6]
[28, 36, 16, 12, 32, 12, 24]


In [19]:
values = [[5 , 8 , 3 , 2 , 7] , [2 , 4 , 5 , 1 , 6] , [3 , 4 , 6 , 7, 8]]
print(values)

[[5, 8, 3, 2, 7], [2, 4, 5, 1, 6], [3, 4, 6, 7, 8]]


In [20]:
import numpy as np

n1 = np.array([7,9,4,3,8,3,6])
print(n1)
print()
print(n1 * 2)

[7 9 4 3 8 3 6]

[14 18  8  6 16  6 12]


In [21]:
print(np.__version__)

2.0.2


In [22]:
print(n1.ndim)
print(n1.shape)

1
(7,)


In [23]:
n2 = np.array([[5 , 8 , 3 , 2 , 7] , [2 , 4 , 5 , 1 , 6] , [3 , 4 , 6 , 7, 8]])
print(n2)

[[5 8 3 2 7]
 [2 4 5 1 6]
 [3 4 6 7 8]]


In [24]:
print(n2 * 3)

[[15 24  9  6 21]
 [ 6 12 15  3 18]
 [ 9 12 18 21 24]]


In [25]:
print(n2)

[[5 8 3 2 7]
 [2 4 5 1 6]
 [3 4 6 7 8]]


In [26]:
print(n2.ndim)
print(n2.shape)
print(n2.size)

2
(3, 5)
15


In [27]:
print(np.mean(n2))
print(np.sum(n2))
print(np.prod(n2))
print(np.min(n2))
print(np.max(n2))
print(np.argmin(n2))
print(np.argmax(n2))

4.733333333333333
71
1625702400
1
8
8
1


In [28]:
n3 = np.array([9,7,3,4,3,7,8,2,1,5,9,3,9])
print(np.min(n3) , np.argmin(n3))
print(np.max(n3) , np.argmax(n3))

1 8
9 0


In [29]:
print(n2)

[[5 8 3 2 7]
 [2 4 5 1 6]
 [3 4 6 7 8]]


In [30]:
#Calculate for each row
print(np.mean(n2, axis = 1))
print(np.sum(n2, axis = 1))
print(np.prod(n2, axis = 1))
print(np.min(n2, axis = 1))
print(np.max(n2, axis = 1))
print(np.argmin(n2, axis = 1))
print(np.argmax(n2, axis = 1))

[5.  3.6 5.6]
[25 18 28]
[1680  240 4032]
[2 1 3]
[8 6 8]
[3 3 0]
[1 4 4]


In [31]:
#Calculate for each columns
print(np.mean(n2, axis = 0))
print(np.sum(n2, axis = 0))
print(np.prod(n2, axis = 0))
print(np.min(n2, axis = 0))
print(np.max(n2, axis = 0))
print(np.argmin(n2, axis = 0))
print(np.argmax(n2, axis = 0))

[3.33333333 5.33333333 4.66666667 3.33333333 7.        ]
[10 16 14 10 21]
[ 30 128  90  14 336]
[2 4 3 1 6]
[5 8 6 7 8]
[1 1 0 1 1]
[0 0 2 2 2]


In [32]:
print(n2)

[[5 8 3 2 7]
 [2 4 5 1 6]
 [3 4 6 7 8]]


In [33]:
print(n2[0,0])            #array[row_index , column_index]
print(n2[0,1])
print(n2[1,0])

5
8
2


In [34]:
print(np.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
print(np.ones((4,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [37]:
n4 = np.arange(0,36)                #array + range
print(n4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [38]:
#36 - (1,36) , (36,1) , (2,18) , (18,2) , (3,12) , (12,3) , (4,9) , (9,4) , (6,6)
n5 = n4.reshape(6,6)
print(n5)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [39]:
print(n2)

[[5 8 3 2 7]
 [2 4 5 1 6]
 [3 4 6 7 8]]


In [40]:
#converting n-dimensional matrix into 1 dimensional
print(n2.ravel())
print(n2.flatten())

[5 8 3 2 7 2 4 5 1 6 3 4 6 7 8]
[5 8 3 2 7 2 4 5 1 6 3 4 6 7 8]


**Broadcasting**

In [41]:
print(n2)

[[5 8 3 2 7]
 [2 4 5 1 6]
 [3 4 6 7 8]]


In [42]:
val = 3

In [43]:
print(n2 * val)

[[15 24  9  6 21]
 [ 6 12 15  3 18]
 [ 9 12 18 21 24]]


In [44]:
a1 = [2,4,2,1,2]

print(n2 * a1)

[[10 32  6  2 14]
 [ 4 16 10  1 12]
 [ 6 16 12  7 16]]


In [45]:
print(n2)

[[5 8 3 2 7]
 [2 4 5 1 6]
 [3 4 6 7 8]]


In [46]:
a2 = [[3],[2],[1]]

print(n2 * a2)

[[15 24  9  6 21]
 [ 4  8 10  2 12]
 [ 3  4  6  7  8]]


In [47]:
print(n2)

[[5 8 3 2 7]
 [2 4 5 1 6]
 [3 4 6 7 8]]


In [48]:
a3 = [[3,2,1,4,1] , [3,2,1,4,1]]

print(n2 * a3)

ValueError: operands could not be broadcast together with shapes (3,5) (2,5) 

**Rules of Broadcasting**
   * a single scaler value can be broadcasted to match the shape of larger array for mathematical operations
   * smaller array should have 1 row and number of coulumns equals to the larger array
   * smaller array should have 1 column and number of rows equals to larger array

**dot product**

In [49]:
print(n2)

[[5 8 3 2 7]
 [2 4 5 1 6]
 [3 4 6 7 8]]


In [50]:
a4 = np.array([[3,2,1,3,4] , [2,1,2,3,2]])
print(a4)

[[3 2 1 3 4]
 [2 1 2 3 2]]


**reshaping** - [3 2 1 3 4 2 1 2 3 2] - [[3, 2] , [1 , 3], [4 , 2] , [1 , 2] , [3 , 2]]

In [51]:
a4.T

array([[3, 2],
       [2, 1],
       [1, 2],
       [3, 3],
       [4, 2]])

In [52]:
np.dot(n2, a4.T)

array([[68, 44],
       [46, 33],
       [76, 59]])

* 3x + 2y + z = 10
* x + y + z = 7
* 2x + 2y + 5z = 15

In [53]:
A = np.array([[3 , 2 , 1] , [1 , 1 , 1] , [2 , 2 , 5]])
print(A)

[[3 2 1]
 [1 1 1]
 [2 2 5]]


In [54]:
X = np.array([['x'] , ['y'] , ['z']])
print(X)

[['x']
 ['y']
 ['z']]


In [55]:
B = np.array([[10] , [7] , [15]])
print(B)

[[10]
 [ 7]
 [15]]


In [56]:
#X = inv(A).B

Ainv = np.linalg.inv(A)

In [57]:
X = np.dot(Ainv, B)
print(X)

[[-3.66666667]
 [10.33333333]
 [ 0.33333333]]


In [58]:
C = np.dot(A,X).astype(int)
print(C)

[[10]
 [ 7]
 [15]]


In [59]:
B == C

array([[ True],
       [ True],
       [ True]])

**Slicing**

In [60]:
arr1 = np.arange(0,42).reshape(6,7)
print(arr1)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [61]:
print(arr1[1,2])              #array[row_index , col_index]

9


* array[row_slicing , column slicing]
* array[intial_row_index : intial_row_index + number of rows , initial_col_index : initial_col_index + number of columns]

In [62]:
print(arr1)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [63]:
print(arr1[2:5 , 1:5])

[[15 16 17 18]
 [22 23 24 25]
 [29 30 31 32]]


In [64]:
arr1[: , 6:]

array([[ 6],
       [13],
       [20],
       [27],
       [34],
       [41]])

In [65]:
arr1[: , -1:]

array([[ 6],
       [13],
       [20],
       [27],
       [34],
       [41]])

In [66]:
arr1[5: , :]

array([[35, 36, 37, 38, 39, 40, 41]])

In [67]:
print(arr1)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [68]:
print(arr1[1:3 , 0:5])

[[ 7  8  9 10 11]
 [14 15 16 17 18]]


In [77]:
print(arr1[4:5 , :])

[[28 29 30 31 32 33 34]]


In [79]:
print(arr1[-2:-1 , :])

[[28 29 30 31 32 33 34]]


In [81]:
print(arr1[:, 5:6])

[[ 5]
 [12]
 [19]
 [26]
 [33]
 [40]]


In [82]:
print(arr1[:, -2:-1])

[[ 5]
 [12]
 [19]
 [26]
 [33]
 [40]]


**Stacking**

  * vertical stack
  * horizontal stack

In [69]:
a = np.array([[2,1,3,4,5], [3,1,5,3,2] , [5,3,2,4,3]])
print(a)

[[2 1 3 4 5]
 [3 1 5 3 2]
 [5 3 2 4 3]]


In [70]:
b = np.array([[7,9,4,3,2] , [3,2,1,5,6]])
print(b)

[[7 9 4 3 2]
 [3 2 1 5 6]]


In [71]:
#vstack - vertical stack
print(np.vstack((a,b)))

[[2 1 3 4 5]
 [3 1 5 3 2]
 [5 3 2 4 3]
 [7 9 4 3 2]
 [3 2 1 5 6]]


In [72]:
print(a)

[[2 1 3 4 5]
 [3 1 5 3 2]
 [5 3 2 4 3]]


In [73]:
c = np.array([[2,3,1],[4,3,2],[2,2,3]])
print(c)

[[2 3 1]
 [4 3 2]
 [2 2 3]]


In [74]:
#hstack - Horizontal stack
print(np.hstack((a,c)))

[[2 1 3 4 5 2 3 1]
 [3 1 5 3 2 4 3 2]
 [5 3 2 4 3 2 2 3]]


**Shallow copy vs Deep Copy**

* It is important because it affects memory usage and data modification behaviour

**Shallow copy (View)**
  * create array a new array object that views the same data in the original array
  * No data is copied
  * changes in one array affects the other

In [83]:
print(arr1)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [84]:
arr2 = arr1[2:5 , 2:6]
print(arr2)

[[16 17 18 19]
 [23 24 25 26]
 [30 31 32 33]]


In [87]:
arr2[0,1] = 1771
print(arr2)

[[  16 1771   18   19]
 [  23   24   25   26]
 [  30   31   32   33]]


In [88]:
print(arr1)

[[   0    1    2    3    4    5    6]
 [   7    8    9   10   11   12   13]
 [  14   15   16 1771   18   19   20]
 [  21   22   23   24   25   26   27]
 [  28   29   30   31   32   33   34]
 [  35   36   37   38   39   40   41]]


**Deep Copy**
  * Creates a completely independent copy of the array and its data in memory
  * data is fully copied
  * Changes in one array do not ad=ffects the other
  * Created using copy()

In [89]:
print(arr1)

[[   0    1    2    3    4    5    6]
 [   7    8    9   10   11   12   13]
 [  14   15   16 1771   18   19   20]
 [  21   22   23   24   25   26   27]
 [  28   29   30   31   32   33   34]
 [  35   36   37   38   39   40   41]]


In [90]:
arr3 = arr1[2:5 , 2:6].copy()
print(arr3)

[[  16 1771   18   19]
 [  23   24   25   26]
 [  30   31   32   33]]


In [92]:
arr3[0,2] =1881
print(arr3)

[[  16 1771 1881   19]
 [  23   24   25   26]
 [  30   31   32   33]]


In [93]:
print(arr1)

[[   0    1    2    3    4    5    6]
 [   7    8    9   10   11   12   13]
 [  14   15   16 1771   18   19   20]
 [  21   22   23   24   25   26   27]
 [  28   29   30   31   32   33   34]
 [  35   36   37   38   39   40   41]]
